### ISSUE TITLE
Unable to import modules.

### ISSUE THREAD

**Issue by andyfenna** [straightdave/eps#5] opened 2016-08-17 14:48 UTC
Hello,

I'm having difficulty importing  your module. If seems to hang when I run the the below from my ps1 script....

`Import-Module "$(Join-Path $solutionPath 'ps-scripts\EPS')" -Force`

The console displays...

`VERBOSE: Loading module from path 'C:\dbgit\db-publish\ps-scripts\EPS\EPS.psd1'.`
`VERBOSE: Loading module from path 'C:\dbgit\db-publish\ps-scripts\EPS\EPS.psm1'.` 

I can't seem to run any code after the import module command, please advise.

Thanks

**Comment by straightdave** [comment] 2016-08-18 01:25
Thanks for your participation. 
But if could, can you please provide your Windows and Powershell runtime version? 

I created a virtual machine on my MAC with Windows 7 and PowerShell 2.0

> to determine the PowerShell version, you can just run
> 
> ```
> Get-Host
> ```
> 
> then it would produce something like
> 
> ```
> Name             : ConsoleHost
> Version          : 2.0
> InstanceId       : xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
> UI               : System.Management.Automation.Internal.Host.InternalHostUserInterface
> CurrentCulture   : zh-CN
> CurrentUICulture : zh-CN
> PrivateData      : Microsoft.PowerShell.ConsoleHost+ConsoleColorProxy
> IsRunspacePushed : False
> Runspace         : System.Management.Automation.Runspaces.LocalRunspace
> ```

Unfortunately, on my machine it works. I just copy the `EPS` folder under my `$PSModulePath`, then run `Import-Module EPS`. After that it showed no error and I can use the commands inside.

**Comment by straightdave** [comment] 2016-08-18 01:53
@dbroeglin how do you think?

**Comment by andyfenna** [comment] 2016-08-18 09:52
Hi @straightdave , I've managed to get this loaded now, thanks for your steady reply.

My intentions are to use this module to move away from Ruby\Rake and erb files. As I want to replace my build\publish CI rake scripts with powershell. And your EPS solution would fit perfectly. However I'm now having a separate issue now, see below..

`powershell : Cannot index into a null array.`
`At line:1 char:1`
`+ powershell .\ps-scripts\publish.ps1 -Verbose`
`+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`
`+ CategoryInfo          : NotSpecified: (Cannot index into a null array.:String) [], RemoteException`
`+ FullyQualifiedErrorId : NativeCommandError`

`At line:1 char:969`
`+ ... :Name=`"Value`">";$_temp += "$($Env[$environment].SSIS.Server)";$_tem ...`
`+                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`
`+ CategoryInfo          : InvalidOperation: (:) [], RuntimeException`
`+ FullyQualifiedErrorId : NullArray`

`Cannot index into a null array.`
`At line:1 char:3104`
`+ ... =`"Value`">";$_temp += "$($Env[$environment].SSIS.SMTP.Server)";$_tem ...`
`+                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`
`+ CategoryInfo          : InvalidOperation: (:) [], RuntimeException`
`+ FullyQualifiedErrorId : NullArray`

`Cannot index into a null array.`
`At line:1 char:4177`
`+ ... ame=`"Value`">";$_temp += "$($Env[$environment].SSIS.DbAlerts)";$_tem ...`
`+                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`
`+ CategoryInfo          : InvalidOperation: (:) [], RuntimeException`
`+ FullyQualifiedErrorId : NullArray`

Please can you advise?

This is my powershell runtuime version.

```
Name             : ConsoleHost
Version          : 5.0.10586.0
InstanceId       : 111e28db-409d-442c-a2b9-4b5e0158be87
UI               : System.Management.Automation.Internal.Host.InternalHostUserInterface
CurrentCulture   : en-GB
CurrentUICulture : en-US
PrivateData      : Microsoft.PowerShell.ConsoleHost+ConsoleColorProxy
DebuggerEnabled  : True
IsRunspacePushed : False
Runspace         : System.Management.Automation.Runspaces.LocalRunspace
```

 Thanks for your support ;)

**Comment by straightdave** [comment] 2016-08-18 12:32
Debugging powershell scripts isn't an easy job.
I don't know why the exception info shows the locations of error are all in 'line:1' (maybe commends of 'publish.ps1' were condensed into one line?). While debugging, the unfolded and well-formatted code is better.
You can follow the info of error locations to see where the exception happens. they at least could tell you which variables invokes error. If a variable triggers 'Cannot index into a null array' error, it might be a list/array unexpectedly to have no results from previous process.
You can put a `$list -eq $null` to check nullability and print their values immediately before they are indexed or iterated.
At last, sorry for those vague and general advise since I've no idea whether the exception you'd seen was caused by EPS or not. Maybe you can provide more information about this?
Thanks again for your information and feedbacks.

**Comment by andyfenna** [comment] 2016-08-18 12:40
Thanks, I'll try to debug it now. Funnily enough the process works as expected the first time you run through ISE, every consecutive time you run after that it seems to give you this error, its very strange!

I'll keep you posted!

**Comment by straightdave** [comment] 2016-08-18 12:45
it sounds like a great clue!! have fun with debugging job today!
as you finished this debugging, i will close this thread. please tell me if you have any founds. 加油！

**Comment by andyfenna** [comment] 2016-08-18 12:55
Hope you can help me out, when I run through cmd prompt i get the error, however when I run through ISE i don't, any ideas?

**Comment by straightdave** [comment] 2016-08-18 13:26
As far as I know, the most frequent mentioned difference between prompt and ISE is `profile`.
You can read [here](http://stackoverflow.com/questions/24851459/how-to-alias-an-executable-using-powershell-permanently/24851786#24851786)  or [there](https://blogs.technet.microsoft.com/heyscriptingguy/2013/01/04/understanding-and-using-powershell-profiles/) to get some knowledge about profiles.
And one point says the ISE would 'remember' functions and aliases between runs of the script. This could relate to your problem.
good luck again.

**Comment by dbroeglin** [comment] 2016-08-20 19:53
Sorry, I did not see this thread earlier. From the error message, I would guess the issue is in the `$Env[$environment]` part of your code. It seems like `$Env` is $Null in your context. Can you check it just before calling the template ? The `$environment` variable seems fine or you would have gotten a NullArrayIndex exception.

I currently do not have access to a windows box and am running on PowerShell 6 on a Mac (still got stars in my eyes about that one), so take the following with a grain of salt. But if i create a template like: `a <%= $Env[$environment] %> a` and then try to expand it without defining `$Env` I get the same kind of error:

```
PS /Users/dom/Sources/eps> Expand-Template -File /tmp/toto
Index operation failed; the array index evaluated to null.
At line:1 char:41
+ $_temp = "";$_temp += "a ";$_temp += "$($Env[$environment])";$_temp + ...
+                                         ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArrayIndex
```

Additionally, `$Env` is usually used as a prefix to access environment variables in the following manner: `$Env:PATH`. In my environment it seems possible to defined a `$Env` variable and then access it. However, it might not work in older versions of PowerShell. Due to the confusion this could create I would definitively shy away from using `Env` as a variable name.

**Comment by straightdave** [comment] 2016-08-24 03:07
Dominique was much more helpful. And close this thread here.

**Closed as completed by straightdave** 2016-08-24 03:07 UTC
