### ISSUE TITLE
Error calling custom functions from the template syntax?

### ISSUE THREAD

**Issue by ellerbus** [straightdave/eps#20] opened 2018-01-03 13:16 UTC
Using the sample code below, I get the following error:

Invoke-EpsTemplate : Exception calling "InvokeWithContext" with "2" argument(s): "The term 'SentenceCase' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again."

Note I'm not using the -Safe switch. Wondering if this is a bug, or a feature? Thanks in advance.

```powershell
Import-Module EPS

function SentenceCase
{
    [CmdletBinding()]
    Param(
        [Parameter(ValueFromPipeline)]
        [String]$word
    )

    return $word.Substring(0, 1).ToUpper() + $word.Substring(1).ToLower()
}

$template = "<%= 'hello' | SentenceCase %>"

$results = Invoke-EpsTemplate -Template $template

Write-Host $results
```

**Comment by ellerbus** [comment] 2018-01-04 13:21
A workaround is to apply the "global" keyword to the function so that it is accessible from within the context of the EPS Module.

```powershell
Import-Module EPS

function global:SentenceCase
{
    [CmdletBinding()]
    Param(
        [Parameter(ValueFromPipeline)]
        [String]$word
    )

    return $word.Substring(0, 1).ToUpper() + $word.Substring(1).ToLower()
}

$template = "<%= 'hello' | SentenceCase %>"

$results = Invoke-EpsTemplate -Template $template

Write-Host $results
```

**Comment by dbroeglin** [comment] 2018-01-04 13:47
Hum, this is strange. Adding `global` in this example should not change anything. To be sure I understand properly. Do you reproduce the bug when you copy and paste your first example into a freshly opened PowerShell console ?

Maybe what you try to do is more complex than this example ? I already had some thought about how we could inject functions in the template scope as we do with _bindings_. However, lacking any concrete example where it might be useful I did not yet add it to the module. If you have a concrete example where it would help I would be very interested.

**Comment by ellerbus** [comment] 2018-01-04 14:21
Yes a new/fresh PowerShell Console accessing EPS as a pure module. The `global` keyword adds my custom function to the global scope. I don't fully understand how modules are scoped with respect to their child / parent scopes, but my custom function is not within the accessible scope of where the template is being executed.

The ability to inject functions similar to -Bindings would be handy, but honestly I'm not opposed to using the `global` keyword as a workaround once I discovered it. My examples don't get much more complex than the sample provided above. My plan is to use EPS to generate source code and will be adding few handy string manipulation helper functions that I'd like to access from my templates.

**Comment by dbroeglin** [comment] 2018-01-04 14:39
OK I will leave the code like that for now. However, I was not able to reproduce it in my environments (MacOSX and Windows 10). Could you be so kind and execute the following code snippet and give us the result ?

```
&{
    $p = Get-Module EPS -ListAvailable
    "Pester version     : " + $p.Version + " " + $p.Path
    "PowerShell version : " + $PSVersionTable.PSVersion
    "OS version         : " + [System.Environment]::OSVersion.VersionString
}
```

BTW, if you are generating code you can look at https://github.com/dbroeglin/Forge.Module which is a module I wrote to generate PS module scaffolds. It is based on EPS and its helper module `Forge` provides a few functions that help in generating code.

**Comment by ellerbus** [comment] 2018-01-04 14:47
```txt
Pester version     : 0.4.0 C:\Program Files\WindowsPowerShell\Modules\EPS\0.4.0\EPS.psd1
PowerShell version : 5.1.15063.786
OS version         : Microsoft Windows NT 10.0.15063.0
```

LOL "Works on my machine"

I took a look at Forge.Module it looks as though it's for creating PowerShell modules, I'm interested in generating source code for other languages.

I'm good with closing this out since I have a work around with `global` and it may work for others.

- Thanks for taking a look

**Comment by dbroeglin** [comment] 2018-01-04 14:50
- You are very welcome!

`Forge.Module` is for generating a PS module, `Forge` however contains the generic code generation functions. You can use it for generating any kind of code. Although I suspect it will be a bit PS oriented. At the very least I hope it will give you some examples of utilising EPS for code generation. Any feedback is welcome ;-)

I will close the issue now. Don't hesitate to get back to us with feedback of how EPS helps (or not) your project :-)

**Closed as completed by dbroeglin** 2018-01-04 14:50 UTC
